# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170519_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='film',
        ),
    ]
