# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 17:01
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_comment_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата комментария')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Film')),
            ],
        ),
    ]
